#  TEAM 2
# D22014	Jay Chothani 
# D22015	Edwin Moses V R
# D22022	Kreena Vipul Sheth
# D22043	Sachin singh

In [1]:
#IMPORTING ALL NECESSARY LIBRARIES
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup

import warnings
warnings.filterwarnings("ignore")

import nltk
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from nltk import word_tokenize
from mlxtend.frequent_patterns import apriori
import requests

# Scrapping reviews from flipkart -PRODUCT--Iphone 13

In [ ]:
list_review=[] #initializing list of reviews
#Starting for loop through all the pages to scrape reviews from all 954 pages
for page in range(2,954):
    SAMPLE_URL1 ="https://www.flipkart.com/apple-iphone-13-midnight-128-gb/product-reviews/itmca361aab1c5b0?pid=MOBG6VF5Q82T3XRS&lid=LSTMOBG6VF5Q82T3XRSOXJLM9&marketplace=FLIPKART&page="+str(page)
    r = requests.get(SAMPLE_URL1)    #getting request from flipkart
    soup = BeautifulSoup(r.content, 'html.parser') #Extracting content through beautiful soup
    co=1 #counter of no of reviews Scraped
    for i in (soup.find_all(class_='t-ZTKy')): #Specific tag class of flipkart page where each review is stored              
        co+=1 #incrementing review counter
        list_review.append(i.text) #Appending reviews to list.

In [ ]:
#creating dictionary to load all the reviews in data frame
dic = {'review':list_review,
      'length':[len(i) for i in list_review]}

In [ ]:
frame=pd.DataFrame(dic) #through pandas creating dataframe

In [ ]:
frame.to_csv('REVIEWS DATA.csv') #saving file to PWD(present working directory)

# TEXT mining

In [2]:
reviews_data = pd.read_csv('REVIEWS DATA.csv') #raeding file

In [3]:
reviews_data = reviews_data.drop(['Unnamed: 0'],axis=1) #droping unneccesary column

In [4]:
#normalizing all the tweets
import string
p = string.punctuation
remv_punc = str.maketrans("", "", p)


from nltk.stem import PorterStemmer
ps = PorterStemmer()

#TEXT PROCESSING---------------
#REMOVING PUNCHUATIONS
#CONVERTING INTO LOWER LETTERS
#REMOVING WHITESPACES
for i in range(len(reviews_data)):
    reviews_data.review[i] = reviews_data.review[i].lower()
    reviews_data.review[i] = reviews_data.review[i].translate(remv_punc)
    reviews_data.review[i] = reviews_data.review[i].replace("  ", " ").strip()

In [5]:
reviews_data

                                                 review  length
0     just shifted from android to ios the new iphon...     242
1     that was quick delivery by flipkartbox is so c...     340
2     its just mindblowing i have switched from andr...     313
3     got it in 2 daysso happy with the phonestarlig...     222
4     first of all this is a nice switch from androi...     507
...                                                 ...     ...
4949  excellent phone with super battery life and ca...      71
4950  i was bit confused before buying but after 10 ...     217
4951   value for money thank you flipkart ‚ù§Ô∏è‚ù§Ô∏èread more      48
4952                              nice productread more      21
4953                               awesome ‚ù§Ô∏èüòçread more      20

[4954 rows x 2 columns]

In [6]:
reviews = (list(reviews_data.review)) #LISTING ALL REVIEWS

In [7]:
from nltk import word_tokenize

In [380]:
#Save the NOUNS only
review_noun=[]
for i in reviews:
    token=word_tokenize(i) #spliting words or we can say tokenizing
    tag=nltk.pos_tag(token) #pos taging
    for j in range(len(tag)):
        if tag[j][1]=='NN': #extracting nouns only
            review_noun.append(tag[j][0])

In [ ]:
unique=list(set(review_noun))    
#creating unique lsit

In [501]:
len(unique)

2508

In [381]:
#craeting dictionary of data of each noun in which review it has occured binarily
dic={}
for nou in unique:
    li=[]
    for i in reviews:
        
        if nou in word_tokenize(i.lower()):
            li.append(1)
        else:
            li.append(0)
        dic[nou]=li

In [ ]:
data = pd.DataFrame(dic)

In [51]:
data

,a15,a15b,abha,absolute,access,accessories,achha,action,activities,ad,...,üòé,üòé4‚≠êÔ∏èprofomance,üòò,üò•premium,üôÇ,ü§†,ü§©,ü§≥quality,ü•∞,ü•≤üëçmobile
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4950,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4951,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4952,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4953,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
data.to_csv('dataframe_noun_without_stemming.csv')

In [14]:
data = pd.read_csv('dataframe_noun_without_stemming.csv')

In [15]:
data = data.drop('Unnamed: 0',axis=1)

In [16]:
data

,a15,a15b,abha,absolute,access,accessories,achha,action,activities,ad,...,üòé,üòé4‚≠êÔ∏èprofomance,üòò,üò•premium,üôÇ,ü§†,ü§©,ü§≥quality,ü•∞,ü•≤üëçmobile
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4949,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4950,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4951,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4952,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4953,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
from mlxtend.frequent_patterns import apriori, association_rules

In [18]:
apr_df = apriori(data, min_support = 0.01, use_colnames = True, max_len=2, verbose = 0) #applying apriori library

C:\Users\Jay Chothani\AppData\Roaming\Python\Python39\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [19]:
apr_df

      support              itemsets
0    0.042188             (amazing)
1    0.014332         (amazingread)
2    0.037344             (android)
3    0.034316               (apple)
4    0.075091             (awesome)
..        ...                   ...
124  0.011506         (nice, phone)
125  0.010295     (nice, phoneread)
126  0.010698          (one, phone)
127  0.013726  (phone, performance)
128  0.011304      (quality, phone)

[129 rows x 2 columns]

# Compactness Pruning

In [20]:
pair_nouns = apr_df.copy() #creating copy

In [21]:
pair_nouns.itemsets[0]

frozenset({'amazing'})

In [22]:
pair = []
for i in range(len(pair_nouns.itemsets)):
    if len(pair_nouns.itemsets[i]) == 2:
        pair += [pair_nouns.itemsets[i]]

In [24]:
pair[0]

frozenset({'amazing', 'phone'})

In [25]:
for i in range(len(pair)):
    pair[i] = list(pair[i])

In [26]:
pair[0]

['amazing', 'phone']

In [27]:
compact = []
for i in range(len(pair)):
        for sentence in reviews:
            sent = word_tokenize(sentence)
            if pair[i][0] in sent and pair[i][1] in sent:
                count = sent.index(pair[i][0]) - sent.index(pair[i][1])
                if abs(count) <4:
                    compact.append((pair[i],sentence))

In [28]:
len(compact)

1866

In [29]:
all_features = []
for i in compact:
    all_features.append(i[0])

In [30]:
features =[]
feature_dic = {}
for i in all_features:
    if i not in features:
        features.append(i)
        feature_dic[str(i[0])+' '+str(i[1])] = 1
    else :
        feature_dic[str(i[0])+' '+str(i[1])] = feature_dic.get(str(i[0])+' '+str(i[1]))+1

In [31]:
features

[['amazing', 'phone'],
 ['android', 'camera'],
 ['android', 'i'],
 ['android', 'ios'],
 ['android', 'iphone'],
 ['android', 'phone'],
 ['i', 'apple'],
 ['apple', 'phone'],
 ['camera', 'awesome'],
 ['awesome', 'phone'],
 ['backup', 'battery'],
 ['camera', 'battery'],
 ['battery', 'good'],
 ['battery', 'i'],
 ['iphone', 'battery'],
 ['life', 'battery'],
 ['battery', 'performance'],
 ['battery', 'phone'],
 ['camera', 'good'],
 ['camera', 'i'],
 ['camera', 'iphone'],
 ['camera', 'performance'],
 ['camera', 'phone'],
 ['camera', 'quality'],
 ['delivery', 'flipkart'],
 ['i', 'experience'],
 ['iphone', 'experience'],
 ['experience', 'phone'],
 ['flipkart', 'i'],
 ['iphone', 'flipkart'],
 ['flipkart', 'phone'],
 ['flipkart', 'thank'],
 ['thanks', 'flipkart'],
 ['good', 'i'],
 ['iphone', 'good'],
 ['good', 'performance'],
 ['good', 'phone'],
 ['good', 'product'],
 ['good', 'productread'],
 ['good', 'quality'],
 ['got', 'i'],
 ['i', 'ios'],
 ['iphone', 'i'],
 ['i', 'itread'],
 ['love', 'i'],
 ['one', 'i'],
 ['i', 'performance'],
 ['i', 'phone'],
 ['i', 'product'],
 ['i', 'quality'],
 ['iphone', 'performance'],
 ['iphone', 'phone'],
 ['love', 'itread'],
 ['nice', 'phone'],
 ['nice', 'phoneread'],
 ['one', 'phone'],
 ['phone', 'performance'],
 ['quality', 'phone']]

# REDUNDANCY PRUNNING

In [32]:
feature_dic

{'amazing phone': 31,
 'android camera': 4,
 'android i': 22,
 'android ios': 49,
 'android iphone': 19,
 'android phone': 13,
 'i apple': 15,
 'apple phone': 13,
 'camera awesome': 49,
 'awesome phone': 52,
 'backup battery': 55,
 'camera battery': 60,
 'battery good': 47,
 'battery i': 6,
 'iphone battery': 7,
 'life battery': 49,
 'battery performance': 44,
 'battery phone': 20,
 'camera good': 54,
 'camera i': 9,
 'camera iphone': 11,
 'camera performance': 62,
 'camera phone': 42,
 'camera quality': 68,
 'delivery flipkart': 25,
 'i experience': 11,
 'iphone experience': 20,
 'experience phone': 11,
 'flipkart i': 10,
 'iphone flipkart': 6,
 'flipkart phone': 10,
 'flipkart thank': 38,
 'thanks flipkart': 51,
 'good i': 28,
 'iphone good': 16,
 'good performance': 31,
 'good phone': 91,
 'good product': 60,
 'good productread': 69,
 'good quality': 26,
 'got i': 34,
 'i ios': 15,
 'iphone i': 61,
 'i itread': 34,
 'love i': 73,
 'one i': 6,
 'i performance': 8,
 'i phone': 110,
 'i product': 28,
 'i quality': 6,
 'iphone performance': 13,
 'iphone phone': 12,
 'love itread': 48,
 'nice phone': 38,
 'nice phoneread': 47,
 'one phone': 4,
 'phone performance': 18,
 'quality phone': 7}

# 2nd (drop column i)

In [33]:
data = data.drop('i',axis=1)

In [34]:
from mlxtend.frequent_patterns import apriori, association_rules

In [35]:
apr_df = apriori(data, min_support = 0.01, use_colnames = True, max_len=2, verbose = 0)

C:\Users\Jay Chothani\AppData\Roaming\Python\Python39\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [36]:
apr_df

      support              itemsets
0    0.042188             (amazing)
1    0.014332         (amazingread)
2    0.037344             (android)
3    0.034316               (apple)
4    0.075091             (awesome)
..        ...                   ...
106  0.011506         (nice, phone)
107  0.010295     (nice, phoneread)
108  0.010698          (one, phone)
109  0.013726  (performance, phone)
110  0.011304      (quality, phone)

[111 rows x 2 columns]

# Compactness Pruning

In [37]:
pair_nouns = apr_df.copy()

In [38]:
pair_nouns.itemsets[0]

frozenset({'amazing'})

In [39]:
pair = []
for i in range(len(pair_nouns.itemsets)):
    if len(pair_nouns.itemsets[i]) == 2:
        pair += [pair_nouns.itemsets[i]]

In [40]:
pair[0]

frozenset({'amazing', 'phone'})

In [41]:
for i in range(len(pair)):
    pair[i] = list(pair[i])

In [42]:
pair[0]

['amazing', 'phone']

In [43]:
compact = []
for i in range(len(pair)):
        for sentence in reviews:
            sent = word_tokenize(sentence)
            if pair[i][0] in sent and pair[i][1] in sent:
                count = sent.index(pair[i][0]) - sent.index(pair[i][1])
                if abs(count) <4:
                    compact.append((pair[i],sentence))

In [44]:
len(compact)

1390

In [45]:
all_features = []
for i in compact:
    all_features.append(i[0])

In [46]:
features =[]
feature_dic = {}
for i in all_features:
    if i not in features:
        features.append(i)
        feature_dic[str(i[0])+' '+str(i[1])] = 1
    else :
        feature_dic[str(i[0])+' '+str(i[1])] = feature_dic.get(str(i[0])+' '+str(i[1]))+1

In [47]:
features

[['amazing', 'phone'],
 ['android', 'camera'],
 ['android', 'ios'],
 ['android', 'iphone'],
 ['android', 'phone'],
 ['apple', 'phone'],
 ['camera', 'awesome'],
 ['awesome', 'phone'],
 ['backup', 'battery'],
 ['camera', 'battery'],
 ['battery', 'good'],
 ['iphone', 'battery'],
 ['life', 'battery'],
 ['battery', 'performance'],
 ['battery', 'phone'],
 ['camera', 'good'],
 ['camera', 'iphone'],
 ['camera', 'performance'],
 ['camera', 'phone'],
 ['camera', 'quality'],
 ['delivery', 'flipkart'],
 ['iphone', 'experience'],
 ['experience', 'phone'],
 ['iphone', 'flipkart'],
 ['flipkart', 'phone'],
 ['flipkart', 'thank'],
 ['thanks', 'flipkart'],
 ['iphone', 'good'],
 ['good', 'performance'],
 ['good', 'phone'],
 ['good', 'product'],
 ['good', 'productread'],
 ['good', 'quality'],
 ['iphone', 'performance'],
 ['iphone', 'phone'],
 ['love', 'itread'],
 ['nice', 'phone'],
 ['nice', 'phoneread'],
 ['one', 'phone'],
 ['performance', 'phone'],
 ['quality', 'phone']]

# REDUNDANCY PRUNNING

In [48]:
feature_dic

{'amazing phone': 31,
 'android camera': 4,
 'android ios': 49,
 'android iphone': 19,
 'android phone': 13,
 'apple phone': 13,
 'camera awesome': 49,
 'awesome phone': 52,
 'backup battery': 55,
 'camera battery': 60,
 'battery good': 47,
 'iphone battery': 7,
 'life battery': 49,
 'battery performance': 44,
 'battery phone': 20,
 'camera good': 54,
 'camera iphone': 11,
 'camera performance': 62,
 'camera phone': 42,
 'camera quality': 68,
 'delivery flipkart': 25,
 'iphone experience': 20,
 'experience phone': 11,
 'iphone flipkart': 6,
 'flipkart phone': 10,
 'flipkart thank': 38,
 'thanks flipkart': 51,
 'iphone good': 16,
 'good performance': 31,
 'good phone': 91,
 'good product': 60,
 'good productread': 69,
 'good quality': 26,
 'iphone performance': 13,
 'iphone phone': 12,
 'love itread': 48,
 'nice phone': 38,
 'nice phoneread': 47,
 'one phone': 4,
 'performance phone': 18,
 'quality phone': 7}

# 3rd ( support 0.005)

In [53]:
apr_df = apriori(data, min_support = 0.005, use_colnames = True, max_len=2, verbose = 0)

C:\Users\Jay Chothani\AppData\Roaming\Python\Python39\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [54]:
apr_df

      support            itemsets
0    0.042188           (amazing)
1    0.014332       (amazingread)
2    0.037344           (android)
3    0.034316             (apple)
4    0.006056         (appleread)
..        ...                 ...
301  0.006459        (use, phone)
302  0.005248      (worth, phone)
303  0.005854  (product, quality)
304  0.005854   (thanks, product)
305  0.005248              (s, ‚Äô)

[306 rows x 2 columns]

# Compactness Pruning

In [55]:
pair_nouns = apr_df.copy()

In [56]:
pair_nouns.itemsets[0]

frozenset({'amazing'})

In [57]:
pair = []
for i in range(len(pair_nouns.itemsets)):
    if len(pair_nouns.itemsets[i]) == 2:
        pair += [pair_nouns.itemsets[i]]

In [58]:
for i in range(len(pair)):
    pair[i] = list(pair[i])

In [59]:
compact = []
for i in range(len(pair)):
        for sentence in reviews:
            sent = word_tokenize(sentence)
            if pair[i][0] in sent and pair[i][1] in sent:
                count = sent.index(pair[i][0]) - sent.index(pair[i][1])
                if abs(count) <4:
                    compact.append((pair[i],sentence))

In [60]:
len(compact)

2952

In [61]:
all_features = []
for i in compact:
    all_features.append(i[0])

In [62]:
features =[]
feature_dic = {}
for i in all_features:
    if i not in features:
        features.append(i)
        feature_dic[str(i[0])+' '+str(i[1])] = 1
    else :
        feature_dic[str(i[0])+' '+str(i[1])] = feature_dic.get(str(i[0])+' '+str(i[1]))+1

In [63]:
features

[['battery', 'amazing'],
 ['camera', 'amazing'],
 ['good', 'amazing'],
 ['iphone', 'amazing'],
 ['amazing', 'phone'],
 ['product', 'amazing'],
 ['android', 'battery'],
 ['android', 'camera'],
 ['android', 'experience'],
 ['android', 'good'],
 ['android', 'ios'],
 ['android', 'iphone'],
 ['android', 'performance'],
 ['android', 'phone'],
 ['android', 'time'],
 ['android', 'user'],
 ['camera', 'apple'],
 ['good', 'apple'],
 ['iphone', 'apple'],
 ['apple', 'phone'],
 ['product', 'apple'],
 ['battery', 'awesome'],
 ['camera', 'awesome'],
 ['experience', 'awesome'],
 ['flipkart', 'awesome'],
 ['good', 'awesome'],
 ['iphone', 'awesome'],
 ['performance', 'awesome'],
 ['awesome', 'phone'],
 ['phoneread', 'awesome'],
 ['product', 'awesome'],
 ['productread', 'awesome'],
 ['backup', 'battery'],
 ['camera', 'backup'],
 ['backup', 'good'],
 ['iphone', 'backup'],
 ['backup', 'phone'],
 ['better', 'battery'],
 ['camera', 'battery'],
 ['display', 'battery'],
 ['battery', 'excellent'],
 ['battery', 'experience'],
 ['flipkart', 'battery'],
 ['battery', 'good'],
 ['got', 'battery'],
 ['iphone', 'battery'],
 ['life', 'battery'],
 ['battery', 'performance'],
 ['battery', 'phone'],
 ['battery', 'product'],
 ['battery', 'quality'],
 ['bbd', 'sale'],
 ['camera', 'better'],
 ['better', 'iphone'],
 ['better', 'phone'],
 ['blowing', 'mind'],
 ['iphone', 'buy'],
 ['buy', 'phone'],
 ['camera', 'day'],
 ['camera', 'design'],
 ['camera', 'display'],
 ['camera', 'excellent'],
 ['camera', 'experience'],
 ['camera', 'good'],
 ['camera', 'ios'],
 ['camera', 'iphone'],
 ['nice', 'camera'],
 ['camera', 'one'],
 ['camera', 'performance'],
 ['camera', 'phone'],
 ['camera', 'product'],
 ['camera', 'quality'],
 ['camera', 'superb'],
 ['camera', 'time'],
 ['flipkart', 'day'],
 ['day', 'phone'],
 ['days', 'phone'],
 ['delivery', 'fast'],
 ['delivery', 'flipkart'],
 ['delivery', 'good'],
 ['iphone', 'delivery'],
 ['delivery', 'phone'],
 ['delivery', 'product'],
 ['thanks', 'delivery'],
 ['good', 'design'],
 ['iphone', 'design'],
 ['design', 'performance'],
 ['display', 'good'],
 ['iphone', 'display'],
 ['display', 'phone'],
 ['everything', 'good'],
 ['iphone', 'excellent'],
 ['excellent', 'phone'],
 ['product', 'excellent'],
 ['good', 'experience'],
 ['experience', 'ios'],
 ['iphone', 'experience'],
 ['experience', 'phone'],
 ['flipkart', 'good'],
 ['got', 'flipkart'],
 ['iphone', 'flipkart'],
 ['flipkart', 'phone'],
 ['flipkart', 'product'],
 ['flipkart', 'thank'],
 ['thanks', 'flipkart'],
 ['flipkartread', 'product'],
 ['flipkartread', 'thank'],
 ['flipkartread', 'thanks'],
 ['genuine', 'product'],
 ['go', 'iphone'],
 ['go', 'itread'],
 ['go', 'phone'],
 ['got', 'good'],
 ['good', 'ios'],
 ['iphone', 'good'],
 ['mobile', 'good'],
 ['nice', 'good'],
 ['one', 'good'],
 ['good', 'performance'],
 ['good', 'phone'],
 ['phoneread', 'good'],
 ['price', 'good'],
 ['good', 'product'],
 ['good', 'productread'],
 ['good', 'quality'],
 ['got', 'iphone'],
 ['got', 'phone'],
 ['iphone', 'ios'],
 ['ios', 'phone'],
 ['iphone', 'life'],
 ['iphone', 'love'],
 ['iphone', 'money'],
 ['one', 'iphone'],
 ['iphone', 'performance'],
 ['iphone', 'phone'],
 ['iphone', 'product'],
 ['iphone', 'quality'],
 ['iphone', 'thanks'],
 ['iphone', 'time'],
 ['iphone', 'user'],
 ['iphone', 'years'],
 ['love', 'itread'],
 ['itread', 'phone'],
 ['love', 'phone'],
 ['value', 'money'],
 ['value', 'moneyread'],
 ['nice', 'phone'],
 ['nice', 'phoneread'],
 ['nice', 'product'],
 ['nice', 'productread'],
 ['one', 'performance'],
 ['one', 'phone'],
 ['performance', 'phone'],
 ['product', 'performance'],
 ['quality', 'performance'],
 ['price', 'phone'],
 ['product', 'phone'],
 ['quality', 'phone'],
 ['read', 'phone'],
 ['sale', 'phone'],
 ['superb', 'phone'],
 ['thank', 'phone'],
 ['time', 'phone'],
 ['use', 'phone'],
 ['worth', 'phone'],
 ['product', 'quality'],
 ['thanks', 'product'],
 ['s', '‚Äô']]

# REDUNDANCY PRUNNING

In [64]:
feature_dic

{'battery amazing': 7,
 'camera amazing': 15,
 'good amazing': 5,
 'iphone amazing': 16,
 'amazing phone': 31,
 'product amazing': 13,
 'android battery': 3,
 'android camera': 4,
 'android experience': 6,
 'android good': 2,
 'android ios': 49,
 'android iphone': 19,
 'android performance': 3,
 'android phone': 13,
 'android time': 9,
 'android user': 24,
 'camera apple': 7,
 'good apple': 3,
 'iphone apple': 7,
 'apple phone': 13,
 'product apple': 21,
 'battery awesome': 16,
 'camera awesome': 49,
 'experience awesome': 12,
 'flipkart awesome': 7,
 'good awesome': 10,
 'iphone awesome': 8,
 'performance awesome': 12,
 'awesome phone': 52,
 'phoneread awesome': 33,
 'product awesome': 28,
 'productread awesome': 31,
 'backup battery': 55,
 'camera backup': 10,
 'backup good': 14,
 'iphone backup': 2,
 'backup phone': 6,
 'better battery': 12,
 'camera battery': 60,
 'display battery': 19,
 'battery excellent': 9,
 'battery experience': 3,
 'flipkart battery': 2,
 'battery good': 47,
 'got battery': 1,
 'iphone battery': 7,
 'life battery': 49,
 'battery performance': 44,
 'battery phone': 20,
 'battery product': 5,
 'battery quality': 19,
 'bbd sale': 28,
 'camera better': 12,
 'better iphone': 10,
 'better phone': 6,
 'blowing mind': 29,
 'iphone buy': 15,
 'buy phone': 12,
 'camera day': 4,
 'camera design': 17,
 'camera display': 16,
 'camera excellent': 19,
 'camera experience': 8,
 'camera good': 54,
 'camera ios': 4,
 'camera iphone': 11,
 'nice camera': 11,
 'camera one': 4,
 'camera performance': 62,
 'camera phone': 42,
 'camera product': 4,
 'camera quality': 68,
 'camera superb': 15,
 'camera time': 3,
 'flipkart day': 3,
 'day phone': 3,
 'days phone': 5,
 'delivery fast': 26,
 'delivery flipkart': 25,
 'delivery good': 17,
 'iphone delivery': 2,
 'delivery phone': 10,
 'delivery product': 9,
 'thanks delivery': 8,
 'good design': 8,
 'iphone design': 2,
 'design performance': 14,
 'display good': 7,
 'iphone display': 3,
 'display phone': 3,
 'everything good': 15,
 'iphone excellent': 10,
 'excellent phone': 33,
 'product excellent': 23,
 'good experience': 13,
 'experience ios': 8,
 'iphone experience': 20,
 'experience phone': 11,
 'flipkart good': 15,
 'got flipkart': 6,
 'iphone flipkart': 6,
 'flipkart phone': 10,
 'flipkart product': 13,
 'flipkart thank': 38,
 'thanks flipkart': 51,
 'flipkartread product': 15,
 'flipkartread thank': 31,
 'flipkartread thanks': 39,
 'genuine product': 23,
 'go iphone': 7,
 'go itread': 37,
 'go phone': 7,
 'got good': 4,
 'good ios': 3,
 'iphone good': 16,
 'mobile good': 13,
 'nice good': 23,
 'one good': 7,
 'good performance': 31,
 'good phone': 91,
 'phoneread good': 36,
 'price good': 13,
 'good product': 60,
 'good productread': 69,
 'good quality': 26,
 'got iphone': 11,
 'got phone': 8,
 'iphone ios': 8,
 'ios phone': 1,
 'iphone life': 5,
 'iphone love': 9,
 'iphone money': 5,
 'one iphone': 5,
 'iphone performance': 13,
 'iphone phone': 12,
 'iphone product': 8,
 'iphone quality': 6,
 'iphone thanks': 7,
 'iphone time': 13,
 'iphone user': 6,
 'iphone years': 4,
 'love itread': 48,
 'itread phone': 11,
 'love phone': 19,
 'value money': 37,
 'value moneyread': 30,
 'nice phone': 38,
 'nice phoneread': 47,
 'nice product': 37,
 'nice productread': 42,
 'one performance': 4,
 'one phone': 4,
 'performance phone': 18,
 'product performance': 8,
 'quality performance': 16,
 'price phone': 15,
 'product phone': 8,
 'quality phone': 7,
 'read phone': 5,
 'sale phone': 1,
 'superb phone': 17,
 'thank phone': 9,
 'time phone': 11,
 'use phone': 8,
 'worth phone': 8,
 'product quality': 12,
 'thanks product': 12,
 's ‚Äô': 25}

##### We like to rate this framework 4 out of 5 in case of automation

# Advantages

1-Easy to understand algorithm

2-We can easily analyse reviews that what people's view about this product and how positive and how negative sentiments are

3-Join and Prune steps are easy to implement on large itemsets in large databases

# Disadvantages

1-It requires high computation if the itemsets are very large and the minimum support is kept very low.


2-The entire database needs to be scanned.

3-High time consuming for large data for creation of data frame of all unique nouns